const pools = [
	{
		name: "POLYGON",
		contractChain: "0x89",
		id: 1,
		contract: {
			name: "CauldronLowRiskV1",
			address: "0xD5Cce7538e9E8DD42d9fdBa3D3edC1D98D9680dA",
			abi: [
				{
					inputs: [
						{
							internalType: "contract IBentoBoxV1",
							name: "bentoBox_",
							type: "address",
						},
						{
							internalType: "contract IERC20",
							name: "magicInternetMoney_",
							type: "address",
						},
					],
					stateMutability: "nonpayable",
					type: "constructor",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: false,
							internalType: "uint128",
							name: "accruedAmount",
							type: "uint128",
						},
					],
					name: "LogAccrue",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "share",
							type: "uint256",
						},
					],
					name: "LogAddCollateral",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "amount",
							type: "uint256",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "part",
							type: "uint256",
						},
					],
					name: "LogBorrow",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: false,
							internalType: "uint256",
							name: "rate",
							type: "uint256",
						},
					],
					name: "LogExchangeRate",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "newFeeTo",
							type: "address",
						},
					],
					name: "LogFeeTo",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "share",
							type: "uint256",
						},
					],
					name: "LogRemoveCollateral",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "amount",
							type: "uint256",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "part",
							type: "uint256",
						},
					],
					name: "LogRepay",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "feeTo",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "feesEarnedFraction",
							type: "uint256",
						},
					],
					name: "LogWithdrawFees",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "previousOwner",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "newOwner",
							type: "address",
						},
					],
					name: "OwnershipTransferred",
					type: "event",
				},
				{
					inputs: [],
					name: "accrue",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "accrueInfo",
					outputs: [
						{ internalType: "uint64", name: "lastAccrued", type: "uint64" },
						{ internalType: "uint128", name: "feesEarned", type: "uint128" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "bool", name: "skim", type: "bool" },
						{ internalType: "uint256", name: "share", type: "uint256" },
					],
					name: "addCollateral",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "bentoBox",
					outputs: [
						{ internalType: "contract IBentoBoxV1", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "borrow",
					outputs: [
						{ internalType: "uint256", name: "part", type: "uint256" },
						{ internalType: "uint256", name: "share", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "claimOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "collateral",
					outputs: [
						{ internalType: "contract IERC20", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "uint8[]", name: "actions", type: "uint8[]" },
						{ internalType: "uint256[]", name: "values", type: "uint256[]" },
						{ internalType: "bytes[]", name: "datas", type: "bytes[]" },
					],
					name: "cook",
					outputs: [
						{ internalType: "uint256", name: "value1", type: "uint256" },
						{ internalType: "uint256", name: "value2", type: "uint256" },
					],
					stateMutability: "payable",
					type: "function",
				},
				{
					inputs: [],
					name: "exchangeRate",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "feeTo",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [{ internalType: "bytes", name: "data", type: "bytes" }],
					name: "init",
					outputs: [],
					stateMutability: "payable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address[]", name: "users", type: "address[]" },
						{
							internalType: "uint256[]",
							name: "maxBorrowParts",
							type: "uint256[]",
						},
						{ internalType: "address", name: "to", type: "address" },
						{
							internalType: "contract ISwapper",
							name: "swapper",
							type: "address",
						},
					],
					name: "liquidate",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "magicInternetMoney",
					outputs: [
						{ internalType: "contract IERC20", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "masterContract",
					outputs: [
						{
							internalType: "contract CauldronLowRiskV1",
							name: "",
							type: "address",
						},
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "oracle",
					outputs: [
						{ internalType: "contract IOracle", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "oracleData",
					outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "owner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "pendingOwner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "reduceSupply",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "share", type: "uint256" },
					],
					name: "removeCollateral",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "bool", name: "skim", type: "bool" },
						{ internalType: "uint256", name: "part", type: "uint256" },
					],
					name: "repay",
					outputs: [
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "newFeeTo", type: "address" },
					],
					name: "setFeeTo",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "totalBorrow",
					outputs: [
						{ internalType: "uint128", name: "elastic", type: "uint128" },
						{ internalType: "uint128", name: "base", type: "uint128" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "totalCollateralShare",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "newOwner", type: "address" },
						{ internalType: "bool", name: "direct", type: "bool" },
						{ internalType: "bool", name: "renounce", type: "bool" },
					],
					name: "transferOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "updateExchangeRate",
					outputs: [
						{ internalType: "bool", name: "updated", type: "bool" },
						{ internalType: "uint256", name: "rate", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "userBorrowPart",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "userCollateralShare",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "withdrawFees",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
			]
		},
		token: {
			name: "WMATIC",
			decimals: 18,
			toFixed: 3,
			address: "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270",
			oracleId: 1,
			oracleDatas: {
				multiply: "0x0000000000000000000000000000000000000000",
				divide: "0x3E7d1eAB13ad0104d2750B8863b489D65364e32D",
				decimals: 34,
			},
			abi: [{ "constant": true, "inputs": [], "name": "name", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "guy", "type": "address" }, { "name": "wad", "type": "uint256" }], "name": "approve", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "totalSupply", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "src", "type": "address" }, { "name": "dst", "type": "address" }, { "name": "wad", "type": "uint256" }], "name": "transferFrom", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "wad", "type": "uint256" }], "name": "withdraw", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "decimals", "outputs": [{ "name": "", "type": "uint8" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "address" }], "name": "balanceOf", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "symbol", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "dst", "type": "address" }, { "name": "wad", "type": "uint256" }], "name": "transfer", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [], "name": "deposit", "outputs": [], "payable": true, "stateMutability": "payable", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "address" }, { "name": "", "type": "address" }], "name": "allowance", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "payable": true, "stateMutability": "payable", "type": "fallback" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "src", "type": "address" }, { "indexed": true, "name": "guy", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Approval", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "src", "type": "address" }, { "indexed": true, "name": "dst", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Transfer", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "dst", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Deposit", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "src", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Withdrawal", "type": "event" }],
		},
		pairToken: {
			name: "AUSD",
			decimals: 18,
			address: "0x9eF75Be5494F7C3EC8097490e3ff50Bf1e182FF1",
			abi: [
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "_owner",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "_spender",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "_value",
							type: "uint256",
						},
					],
					name: "Approval",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "previousOwner",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "newOwner",
							type: "address",
						},
					],
					name: "OwnershipTransferred",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "_from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "_to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "_value",
							type: "uint256",
						},
					],
					name: "Transfer",
					type: "event",
				},
				{
					inputs: [],
					name: "DOMAIN_SEPARATOR",
					outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "", type: "address" },
						{ internalType: "address", name: "", type: "address" },
					],
					name: "allowance",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "spender", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "approve",
					outputs: [{ internalType: "bool", name: "", type: "bool" }],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "balanceOf",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "burn",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "claimOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "decimals",
					outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "lastMint",
					outputs: [
						{ internalType: "uint128", name: "time", type: "uint128" },
						{ internalType: "uint128", name: "amount", type: "uint128" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "mint",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "clone", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
						{
							internalType: "contract IBentoBoxV1",
							name: "bentoBox",
							type: "address",
						},
					],
					name: "mintToBentoBox",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "name",
					outputs: [{ internalType: "string", name: "", type: "string" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "nonces",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "owner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "pendingOwner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "owner_", type: "address" },
						{ internalType: "address", name: "spender", type: "address" },
						{ internalType: "uint256", name: "value", type: "uint256" },
						{ internalType: "uint256", name: "deadline", type: "uint256" },
						{ internalType: "uint8", name: "v", type: "uint8" },
						{ internalType: "bytes32", name: "r", type: "bytes32" },
						{ internalType: "bytes32", name: "s", type: "bytes32" },
					],
					name: "permit",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "symbol",
					outputs: [{ internalType: "string", name: "", type: "string" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "totalSupply",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "transfer",
					outputs: [{ internalType: "bool", name: "", type: "bool" }],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "from", type: "address" },
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "transferFrom",
					outputs: [{ internalType: "bool", name: "", type: "bool" }],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "newOwner", type: "address" },
						{ internalType: "bool", name: "direct", type: "bool" },
						{ internalType: "bool", name: "renounce", type: "bool" },
					],
					name: "transferOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
			],
		},
		stabilityFee: 8,
		interest: 1,
		ltv: 75,
		initialMax: 20,
		swapContractInfo: {
			address: "0x197De282d7b5cEFfFD8f8B0196c30e8401593CF6",
			abi: [
				{
					inputs: [
						{
							internalType: "contract IBentoBoxV1",
							name: "bentoBox_",
							type: "address",
						},
					],
					stateMutability: "nonpayable",
					type: "constructor",
				},
				{
					inputs: [],
					name: "MIM",
					outputs: [
						{ internalType: "contract IERC20", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "MIM3POOL",
					outputs: [
						{ internalType: "contract CurvePool", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "TETHER",
					outputs: [
						{ internalType: "contract TetherToken", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "USDT_VAULT",
					outputs: [
						{ internalType: "contract YearnVault", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "bentoBox",
					outputs: [
						{ internalType: "contract IBentoBoxV1", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "recipient", type: "address" },
						{ internalType: "uint256", name: "shareToMin", type: "uint256" },
						{ internalType: "uint256", name: "shareFrom", type: "uint256" },
					],
					name: "swap",
					outputs: [
						{ internalType: "uint256", name: "extraShare", type: "uint256" },
						{ internalType: "uint256", name: "shareReturned", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
			],
		},
	},
	{
		name: "DFYN",
		contractChain: "0x89",
		id: 2,
		contract: {
			name: "CauldronLowRiskV1",
			address: "0xF398F05838e53050559Eb02AA09c87BB0Fe4e71C",
			abi: [
				{
					inputs: [
						{
							internalType: "contract IBentoBoxV1",
							name: "bentoBox_",
							type: "address",
						},
						{
							internalType: "contract IERC20",
							name: "magicInternetMoney_",
							type: "address",
						},
					],
					stateMutability: "nonpayable",
					type: "constructor",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: false,
							internalType: "uint128",
							name: "accruedAmount",
							type: "uint128",
						},
					],
					name: "LogAccrue",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "share",
							type: "uint256",
						},
					],
					name: "LogAddCollateral",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "amount",
							type: "uint256",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "part",
							type: "uint256",
						},
					],
					name: "LogBorrow",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: false,
							internalType: "uint256",
							name: "rate",
							type: "uint256",
						},
					],
					name: "LogExchangeRate",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "newFeeTo",
							type: "address",
						},
					],
					name: "LogFeeTo",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "share",
							type: "uint256",
						},
					],
					name: "LogRemoveCollateral",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "amount",
							type: "uint256",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "part",
							type: "uint256",
						},
					],
					name: "LogRepay",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "feeTo",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "feesEarnedFraction",
							type: "uint256",
						},
					],
					name: "LogWithdrawFees",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "previousOwner",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "newOwner",
							type: "address",
						},
					],
					name: "OwnershipTransferred",
					type: "event",
				},
				{
					inputs: [],
					name: "accrue",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "accrueInfo",
					outputs: [
						{ internalType: "uint64", name: "lastAccrued", type: "uint64" },
						{ internalType: "uint128", name: "feesEarned", type: "uint128" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "bool", name: "skim", type: "bool" },
						{ internalType: "uint256", name: "share", type: "uint256" },
					],
					name: "addCollateral",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "bentoBox",
					outputs: [
						{ internalType: "contract IBentoBoxV1", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "borrow",
					outputs: [
						{ internalType: "uint256", name: "part", type: "uint256" },
						{ internalType: "uint256", name: "share", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "claimOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "collateral",
					outputs: [
						{ internalType: "contract IERC20", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "uint8[]", name: "actions", type: "uint8[]" },
						{ internalType: "uint256[]", name: "values", type: "uint256[]" },
						{ internalType: "bytes[]", name: "datas", type: "bytes[]" },
					],
					name: "cook",
					outputs: [
						{ internalType: "uint256", name: "value1", type: "uint256" },
						{ internalType: "uint256", name: "value2", type: "uint256" },
					],
					stateMutability: "payable",
					type: "function",
				},
				{
					inputs: [],
					name: "exchangeRate",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "feeTo",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [{ internalType: "bytes", name: "data", type: "bytes" }],
					name: "init",
					outputs: [],
					stateMutability: "payable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address[]", name: "users", type: "address[]" },
						{
							internalType: "uint256[]",
							name: "maxBorrowParts",
							type: "uint256[]",
						},
						{ internalType: "address", name: "to", type: "address" },
						{
							internalType: "contract ISwapper",
							name: "swapper",
							type: "address",
						},
					],
					name: "liquidate",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "magicInternetMoney",
					outputs: [
						{ internalType: "contract IERC20", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "masterContract",
					outputs: [
						{
							internalType: "contract CauldronLowRiskV1",
							name: "",
							type: "address",
						},
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "oracle",
					outputs: [
						{ internalType: "contract IOracle", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "oracleData",
					outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "owner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "pendingOwner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "reduceSupply",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "share", type: "uint256" },
					],
					name: "removeCollateral",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "bool", name: "skim", type: "bool" },
						{ internalType: "uint256", name: "part", type: "uint256" },
					],
					name: "repay",
					outputs: [
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "newFeeTo", type: "address" },
					],
					name: "setFeeTo",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "totalBorrow",
					outputs: [
						{ internalType: "uint128", name: "elastic", type: "uint128" },
						{ internalType: "uint128", name: "base", type: "uint128" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "totalCollateralShare",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "newOwner", type: "address" },
						{ internalType: "bool", name: "direct", type: "bool" },
						{ internalType: "bool", name: "renounce", type: "bool" },
					],
					name: "transferOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "updateExchangeRate",
					outputs: [
						{ internalType: "bool", name: "updated", type: "bool" },
						{ internalType: "uint256", name: "rate", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "userBorrowPart",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "userCollateralShare",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "withdrawFees",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
			],
		},
		token: {
			name: "DFYN",
			decimals: 18,
			toFixed: 3,
			address: "0xc168e40227e4ebd8c1cae80f7a55a4f0e6d66c97",
			oracleId: 2,
			oracleDatas: {
				multiply: "0x0000000000000000000000000000000000000000",
				divide: "0x3E7d1eAB13ad0104d2750B8863b489D65364e32D",
				decimals: 34,
			},
			abi: [{ "constant": true, "inputs": [], "name": "name", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "guy", "type": "address" }, { "name": "wad", "type": "uint256" }], "name": "approve", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "totalSupply", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "src", "type": "address" }, { "name": "dst", "type": "address" }, { "name": "wad", "type": "uint256" }], "name": "transferFrom", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "wad", "type": "uint256" }], "name": "withdraw", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "decimals", "outputs": [{ "name": "", "type": "uint8" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "address" }], "name": "balanceOf", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "symbol", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "dst", "type": "address" }, { "name": "wad", "type": "uint256" }], "name": "transfer", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [], "name": "deposit", "outputs": [], "payable": true, "stateMutability": "payable", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "address" }, { "name": "", "type": "address" }], "name": "allowance", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "payable": true, "stateMutability": "payable", "type": "fallback" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "src", "type": "address" }, { "indexed": true, "name": "guy", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Approval", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "src", "type": "address" }, { "indexed": true, "name": "dst", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Transfer", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "dst", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Deposit", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "src", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Withdrawal", "type": "event" }],
		},
		pairToken: {
			name: "AUSD",
			decimals: 18,
			address: "0x9eF75Be5494F7C3EC8097490e3ff50Bf1e182FF1",
			abi: [
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "_owner",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "_spender",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "_value",
							type: "uint256",
						},
					],
					name: "Approval",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "previousOwner",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "newOwner",
							type: "address",
						},
					],
					name: "OwnershipTransferred",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "_from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "_to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "_value",
							type: "uint256",
						},
					],
					name: "Transfer",
					type: "event",
				},
				{
					inputs: [],
					name: "DOMAIN_SEPARATOR",
					outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "", type: "address" },
						{ internalType: "address", name: "", type: "address" },
					],
					name: "allowance",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "spender", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "approve",
					outputs: [{ internalType: "bool", name: "", type: "bool" }],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "balanceOf",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "burn",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "claimOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "decimals",
					outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "lastMint",
					outputs: [
						{ internalType: "uint128", name: "time", type: "uint128" },
						{ internalType: "uint128", name: "amount", type: "uint128" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "mint",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "clone", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
						{
							internalType: "contract IBentoBoxV1",
							name: "bentoBox",
							type: "address",
						},
					],
					name: "mintToBentoBox",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "name",
					outputs: [{ internalType: "string", name: "", type: "string" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "nonces",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "owner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "pendingOwner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "owner_", type: "address" },
						{ internalType: "address", name: "spender", type: "address" },
						{ internalType: "uint256", name: "value", type: "uint256" },
						{ internalType: "uint256", name: "deadline", type: "uint256" },
						{ internalType: "uint8", name: "v", type: "uint8" },
						{ internalType: "bytes32", name: "r", type: "bytes32" },
						{ internalType: "bytes32", name: "s", type: "bytes32" },
					],
					name: "permit",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "symbol",
					outputs: [{ internalType: "string", name: "", type: "string" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "totalSupply",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "transfer",
					outputs: [{ internalType: "bool", name: "", type: "bool" }],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "from", type: "address" },
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "transferFrom",
					outputs: [{ internalType: "bool", name: "", type: "bool" }],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "newOwner", type: "address" },
						{ internalType: "bool", name: "direct", type: "bool" },
						{ internalType: "bool", name: "renounce", type: "bool" },
					],
					name: "transferOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
			],
		},
		stabilityFee: 8,
		interest: 1,
		ltv: 75,
		initialMax: 20,
		swapContractInfo: {
			address: "0x197De282d7b5cEFfFD8f8B0196c30e8401593CF6",
			abi: [
				{
					inputs: [
						{
							internalType: "contract IBentoBoxV1",
							name: "bentoBox_",
							type: "address",
						},
					],
					stateMutability: "nonpayable",
					type: "constructor",
				},
				{
					inputs: [],
					name: "MIM",
					outputs: [
						{ internalType: "contract IERC20", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "MIM3POOL",
					outputs: [
						{ internalType: "contract CurvePool", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "TETHER",
					outputs: [
						{ internalType: "contract TetherToken", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "USDT_VAULT",
					outputs: [
						{ internalType: "contract YearnVault", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "bentoBox",
					outputs: [
						{ internalType: "contract IBentoBoxV1", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "recipient", type: "address" },
						{ internalType: "uint256", name: "shareToMin", type: "uint256" },
						{ internalType: "uint256", name: "shareFrom", type: "uint256" },
					],
					name: "swap",
					outputs: [
						{ internalType: "uint256", name: "extraShare", type: "uint256" },
						{ internalType: "uint256", name: "shareReturned", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
			],
		},
	},
	{
		name: "ETHEREUM",
		contractChain: "0x89",
		id: 3,
		contract: {
			name: "CauldronLowRiskV1",
			address: "0x0562ca45C9ab77d02Dc5d39FeaD3A61E29dbC90a",
			abi: [
				{
					inputs: [
						{
							internalType: "contract IBentoBoxV1",
							name: "bentoBox_",
							type: "address",
						},
						{
							internalType: "contract IERC20",
							name: "magicInternetMoney_",
							type: "address",
						},
					],
					stateMutability: "nonpayable",
					type: "constructor",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: false,
							internalType: "uint128",
							name: "accruedAmount",
							type: "uint128",
						},
					],
					name: "LogAccrue",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "share",
							type: "uint256",
						},
					],
					name: "LogAddCollateral",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "amount",
							type: "uint256",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "part",
							type: "uint256",
						},
					],
					name: "LogBorrow",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: false,
							internalType: "uint256",
							name: "rate",
							type: "uint256",
						},
					],
					name: "LogExchangeRate",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "newFeeTo",
							type: "address",
						},
					],
					name: "LogFeeTo",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "share",
							type: "uint256",
						},
					],
					name: "LogRemoveCollateral",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "amount",
							type: "uint256",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "part",
							type: "uint256",
						},
					],
					name: "LogRepay",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "feeTo",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "feesEarnedFraction",
							type: "uint256",
						},
					],
					name: "LogWithdrawFees",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "previousOwner",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "newOwner",
							type: "address",
						},
					],
					name: "OwnershipTransferred",
					type: "event",
				},
				{
					inputs: [],
					name: "accrue",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "accrueInfo",
					outputs: [
						{ internalType: "uint64", name: "lastAccrued", type: "uint64" },
						{ internalType: "uint128", name: "feesEarned", type: "uint128" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "bool", name: "skim", type: "bool" },
						{ internalType: "uint256", name: "share", type: "uint256" },
					],
					name: "addCollateral",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "bentoBox",
					outputs: [
						{ internalType: "contract IBentoBoxV1", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "borrow",
					outputs: [
						{ internalType: "uint256", name: "part", type: "uint256" },
						{ internalType: "uint256", name: "share", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "claimOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "collateral",
					outputs: [
						{ internalType: "contract IERC20", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "uint8[]", name: "actions", type: "uint8[]" },
						{ internalType: "uint256[]", name: "values", type: "uint256[]" },
						{ internalType: "bytes[]", name: "datas", type: "bytes[]" },
					],
					name: "cook",
					outputs: [
						{ internalType: "uint256", name: "value1", type: "uint256" },
						{ internalType: "uint256", name: "value2", type: "uint256" },
					],
					stateMutability: "payable",
					type: "function",
				},
				{
					inputs: [],
					name: "exchangeRate",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "feeTo",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [{ internalType: "bytes", name: "data", type: "bytes" }],
					name: "init",
					outputs: [],
					stateMutability: "payable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address[]", name: "users", type: "address[]" },
						{
							internalType: "uint256[]",
							name: "maxBorrowParts",
							type: "uint256[]",
						},
						{ internalType: "address", name: "to", type: "address" },
						{
							internalType: "contract ISwapper",
							name: "swapper",
							type: "address",
						},
					],
					name: "liquidate",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "magicInternetMoney",
					outputs: [
						{ internalType: "contract IERC20", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "masterContract",
					outputs: [
						{
							internalType: "contract CauldronLowRiskV1",
							name: "",
							type: "address",
						},
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "oracle",
					outputs: [
						{ internalType: "contract IOracle", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "oracleData",
					outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "owner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "pendingOwner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "reduceSupply",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "share", type: "uint256" },
					],
					name: "removeCollateral",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "bool", name: "skim", type: "bool" },
						{ internalType: "uint256", name: "part", type: "uint256" },
					],
					name: "repay",
					outputs: [
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "newFeeTo", type: "address" },
					],
					name: "setFeeTo",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "totalBorrow",
					outputs: [
						{ internalType: "uint128", name: "elastic", type: "uint128" },
						{ internalType: "uint128", name: "base", type: "uint128" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "totalCollateralShare",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "newOwner", type: "address" },
						{ internalType: "bool", name: "direct", type: "bool" },
						{ internalType: "bool", name: "renounce", type: "bool" },
					],
					name: "transferOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "updateExchangeRate",
					outputs: [
						{ internalType: "bool", name: "updated", type: "bool" },
						{ internalType: "uint256", name: "rate", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "userBorrowPart",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "userCollateralShare",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "withdrawFees",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
			],
		},
		token: {
			name: "WETH",
			decimals: 18,
			toFixed: 3,
			address: "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619",
			oracleId: 3,
			oracleDatas: {
				multiply: "0x0000000000000000000000000000000000000000",
				divide: "0x3E7d1eAB13ad0104d2750B8863b489D65364e32D",
				decimals: 34,
			},
			abi: [{ "constant": true, "inputs": [], "name": "name", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "guy", "type": "address" }, { "name": "wad", "type": "uint256" }], "name": "approve", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "totalSupply", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "src", "type": "address" }, { "name": "dst", "type": "address" }, { "name": "wad", "type": "uint256" }], "name": "transferFrom", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "wad", "type": "uint256" }], "name": "withdraw", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "decimals", "outputs": [{ "name": "", "type": "uint8" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "address" }], "name": "balanceOf", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "symbol", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "dst", "type": "address" }, { "name": "wad", "type": "uint256" }], "name": "transfer", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [], "name": "deposit", "outputs": [], "payable": true, "stateMutability": "payable", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "address" }, { "name": "", "type": "address" }], "name": "allowance", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "payable": true, "stateMutability": "payable", "type": "fallback" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "src", "type": "address" }, { "indexed": true, "name": "guy", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Approval", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "src", "type": "address" }, { "indexed": true, "name": "dst", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Transfer", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "dst", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Deposit", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "src", "type": "address" }, { "indexed": false, "name": "wad", "type": "uint256" }], "name": "Withdrawal", "type": "event" }],
		},
		pairToken: {
			name: "AUSD",
			decimals: 18,
			address: "0x9eF75Be5494F7C3EC8097490e3ff50Bf1e182FF1",
			abi: [
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "_owner",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "_spender",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "_value",
							type: "uint256",
						},
					],
					name: "Approval",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "previousOwner",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "newOwner",
							type: "address",
						},
					],
					name: "OwnershipTransferred",
					type: "event",
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "_from",
							type: "address",
						},
						{
							indexed: true,
							internalType: "address",
							name: "_to",
							type: "address",
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "_value",
							type: "uint256",
						},
					],
					name: "Transfer",
					type: "event",
				},
				{
					inputs: [],
					name: "DOMAIN_SEPARATOR",
					outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "", type: "address" },
						{ internalType: "address", name: "", type: "address" },
					],
					name: "allowance",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "spender", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "approve",
					outputs: [{ internalType: "bool", name: "", type: "bool" }],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "balanceOf",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "burn",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "claimOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "decimals",
					outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "lastMint",
					outputs: [
						{ internalType: "uint128", name: "time", type: "uint128" },
						{ internalType: "uint128", name: "amount", type: "uint128" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "mint",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "clone", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
						{
							internalType: "contract IBentoBoxV1",
							name: "bentoBox",
							type: "address",
						},
					],
					name: "mintToBentoBox",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "name",
					outputs: [{ internalType: "string", name: "", type: "string" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [{ internalType: "address", name: "", type: "address" }],
					name: "nonces",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "owner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "pendingOwner",
					outputs: [{ internalType: "address", name: "", type: "address" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "owner_", type: "address" },
						{ internalType: "address", name: "spender", type: "address" },
						{ internalType: "uint256", name: "value", type: "uint256" },
						{ internalType: "uint256", name: "deadline", type: "uint256" },
						{ internalType: "uint8", name: "v", type: "uint8" },
						{ internalType: "bytes32", name: "r", type: "bytes32" },
						{ internalType: "bytes32", name: "s", type: "bytes32" },
					],
					name: "permit",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [],
					name: "symbol",
					outputs: [{ internalType: "string", name: "", type: "string" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "totalSupply",
					outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "transfer",
					outputs: [{ internalType: "bool", name: "", type: "bool" }],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "from", type: "address" },
						{ internalType: "address", name: "to", type: "address" },
						{ internalType: "uint256", name: "amount", type: "uint256" },
					],
					name: "transferFrom",
					outputs: [{ internalType: "bool", name: "", type: "bool" }],
					stateMutability: "nonpayable",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "newOwner", type: "address" },
						{ internalType: "bool", name: "direct", type: "bool" },
						{ internalType: "bool", name: "renounce", type: "bool" },
					],
					name: "transferOwnership",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function",
				},
			],
		},
		stabilityFee: 8,
		interest: 1,
		ltv: 75,
		initialMax: 20,
		swapContractInfo: {
			address: "0x197De282d7b5cEFfFD8f8B0196c30e8401593CF6",
			abi: [
				{
					inputs: [
						{
							internalType: "contract IBentoBoxV1",
							name: "bentoBox_",
							type: "address",
						},
					],
					stateMutability: "nonpayable",
					type: "constructor",
				},
				{
					inputs: [],
					name: "MIM",
					outputs: [
						{ internalType: "contract IERC20", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "MIM3POOL",
					outputs: [
						{ internalType: "contract CurvePool", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "TETHER",
					outputs: [
						{ internalType: "contract TetherToken", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "USDT_VAULT",
					outputs: [
						{ internalType: "contract YearnVault", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [],
					name: "bentoBox",
					outputs: [
						{ internalType: "contract IBentoBoxV1", name: "", type: "address" },
					],
					stateMutability: "view",
					type: "function",
				},
				{
					inputs: [
						{ internalType: "address", name: "recipient", type: "address" },
						{ internalType: "uint256", name: "shareToMin", type: "uint256" },
						{ internalType: "uint256", name: "shareFrom", type: "uint256" },
					],
					name: "swap",
					outputs: [
						{ internalType: "uint256", name: "extraShare", type: "uint256" },
						{ internalType: "uint256", name: "shareReturned", type: "uint256" },
					],
					stateMutability: "nonpayable",
					type: "function",
				},
			],
		},
	}
];

export default pools